### ISSUE TITLE
Components we need ...

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/owncloud-design-system#10]
vuetify components as used today in phoenix:

- [x] v-alert
- [x] v-autocomplete
- [x] v-avatar
- [x] v-bottom-sheet
- [x] v-breadcrumbs
- [x] v-btn
- [x] v-card
- [x] v-card-actions
- [x] v-card-text
- [x] v-card-title
- [x] v-checkbox
- [x] v-container
- [x] v-content
- [x] v-dialog
- [x] v-divider
- [x] v-flex
- [x] v-footer
- [x] v-icon
- [x] v-img
- [x] v-layout
- [x] v-list
- [x] v-list-group
- [x] v-list-tile
- [x] v-list-tile-action
- [x] v-list-tile-action-text
- [x] v-list-tile-avatar
- [x] v-list-tile-content
- [x] v-list-tile-sub-title
- [x] v-list-tile-title
- [x] v-menu
- [x] v-navigation-drawer
- [x] v-progress-circular
- [x] v-progress-linear
- [x] v-radio
- [x] v-radio-group
- [x] v-snackbar
- [x] v-spacer
- [x] v-subheader
- [x] v-switch
- [x] v-tab
- [x] v-tab-item
- [x] v-tabs
- [x] v-textarea
- [x] v-text-field

**Comment by scramb** [comment]
closing in favor of #12
