### ISSUE TITLE
Reduce memory load & bundle size in development

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/owncloud-design-system#1142]
While spending a lot of time inside the design system recently, there's two (perhaps interconnected) points that I want to point out and which we should fix sometime soon:

1. I suspect that we're generating & importing a lot more CSS than necessary in development mode, see a screenshot below. This is only the case in development though, neither the running `web.owncloud.com` nor building the ODS asset bundle and linking it locally in `web` produce the same problem.

<img width="254" alt="Screenshot 2021-03-11 at 17 58 20" src="https://user-images.githubusercontent.com/16822008/110839401-691d4600-829b-11eb-8ab8-927472828676.png">

2. Running `yarn start` in the ODS project sometimes turns into a performance issue on my Mac M1, eventually grinding the whole system to the point where even the sound starts taking breaks 😅 Maybe it's just me and I guess Vue3 + Rollup will bring some remedy soon, but perhaps we can reduce what's going on in `npm-run-all --parallel styleguide theo:onchange theo dev` (spinning up 4 node processes and a lot of computation based on changes in (S)CSS files) - and maybe that's related to point **1**?

**Comment by pascalwengerter** [comment]
@fschade @kulmann @paulcod3 @LukasHirt can we tackle this in the next sprint? I can't use the local preview of the docs anymore on my 8GB M1 MacBook

**Comment by fschade** [comment]
That’s a huge topic which also involves the build system and docs. Not sure if that’s something we could tackle in only one sprint.

**Comment by pascalwengerter** [comment]
Agreed, still we need to bring this back into at least an acceptable state where an average laptop model can be used for reviews & local code testing. Perhaps some Webpack config tweaks bring us (back) there again without having a perfect solution

**Comment by paulcod3** [comment]
hm im not sure, the build runs pretty quick on my machine or am I misunderstanding something?

**Comment by LukasHirt** [comment]
> That’s a huge topic which also involves the build system

Since it's critical for the docs, we could easily split the task for docs and for system. Those are completely separated processes as one is based on vue-styleguidist and one only on webpack.

**Comment by pascalwengerter** [comment]
With the move of the ODS to `web`, [introduction of Vite](https://github.com/owncloud/web/pull/7952) and [deduplication of CSS](https://github.com/owncloud/web/pull/8041) I think we can close this issue :)
