### ISSUE TITLE
Elements and their creation...

### ISSUE THREAD

**Issue by scramb** [owncloud/owncloud-design-system#12]
### Description
First of all we need basic elements to start build patterns on top.

To ensure painless creation we should start to build all already used elements we used from vuetify. In my opinion this does not include things as OcList for example since OcList ist using alot of v- components inside. 

### My proposed break-down of what's to do and when to do:
 
- [x] icons, buttons and navigations - ELEMENTS
  - [x] v-icon
  - [x] v-btn
  - [x] v-img
  - [x] v-radio
  - [x] v-checkbox
  - [x] v-text-field
  - [x] v-textarea
  - [x] v-switch
- [ ] fancy stuff - ELEMENTS
  - [x] v-alert
  - [x] v-avatar
  - [x] v-snackbar
  - [x] v-progress-circular
  - [x] v-progress-linear
  - [ ] v-autocomplete
- [ ] left-overs - ELEMENTS  (tbd)
  - [ ] v-card
  - [ ] v-card-stuff
  - [ ] v-dialog
  - [ ] v-footer
  - [x] v-menu
- [ ] discuss further use of layout components like v-flex
- [ ] discuss further use of spacer/helper components vs (spacing-)helpers as proposed by vueds
- [ ] discuss & start building patterns out of existing components like:
    - [x] OcList
    - [ ] ...
#### Patterns
- [x] v-breadcrumb #17 
- [x] v-list(-group) and insides #19 
- [ ] v-radio-group

#### NotSortedYet
- [ ] v-bottom-sheet
- [ ] v-navigation-drawer
- [ ] v-subheader
- [ ] v-tab(-item/tabs)
#### LayoutComps and style-helpers (tbd)
- [ ] v-container
- [ ] v-content
- [ ] v-divider
- [ ] v-spacer
- [ ] v-flex
- [ ] v-layout

**Comment by felixheidecke** [comment]
I created a component called `OcFile` which displays a file along with the appropriate icon and the extension. The API does not yet return the mime-type which would be really really nice to have that in order to know if its text, image, video or whatever and determine whether there can be file previews or not.

**Comment by DeepDiver1975** [comment]
> The API does not yet return the mime-type which would be really really nice to have that in order to know if its text, image, video or whatever and determine whether there can be file previews or not.

we have this available in phoenix - see https://github.com/owncloud/phoenix/blob/6c8f5d928a42fb00af57919f3af20a98b8026ce8/apps/files/src/mixins.js#L88 and https://github.com/owncloud/phoenix/blob/master/apps/files/src/fileTypeIconMappings.json

**Comment by DeepDiver1975** [comment]
all missing components got their own issues -> closing
