### ISSUE TITLE
oc-file-actions: missing props ...

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/owncloud-design-system#127]
- [ ] property actions is missing - there is no way to control the actions from out side the component - example code works by accident from my understanding
- [ ] toggling the component should be done via an bound variable - just like everywhere else
- [ ] same for the file name

^ we have all these information available in the vuex store - just need to connect stuff ...

**Comment by butonic** [comment]
1. actions for the file are passed in the event like in https://github.com/owncloud/owncloud-design-system/blob/master/src/patterns/OcFileActions.vue#L173 and in https://github.com/owncloud/owncloud-design-system/blob/master/src/templates/Files.vue#L258-L261
While that works as designed the parameter payload should probably not be called `file`. Maybe stich with `payload, as it contains a `file` object and an `actions` array.

2. toggling via a bound variable creates a coupling between the file actions and the template it is being used on. using events is less coupled, IMO. If we want the file actions to be triggered from anywhere in the UI doing that via a shared state requires more work than by using the global event system.

3. file name is passed in via the event as well.

it might make sense to pull all this from the store. @felixheidecke mentioned something like that ... but it was a little outside my vue comfort zone.

**Comment by DeepDiver1975** [comment]
>     1. https://github.com/owncloud/owncloud-design-system/blob/master/src/templates/Files.vue#L258-L261

I was missing this part ... let me retry this .... still not convinced in my vue comfort zone ;-)

**Comment by DeepDiver1975** [comment]
works - no need to change anything -> closing
