### ISSUE TITLE
Use OcSelect component for OcAutocomplete internally

### ISSUE THREAD

**Issue by kulmann** [owncloud/owncloud-design-system#1289]
We brought the `vue-select` component into our design system as `OcSelect` component for various reasons. Details can be found here: https://github.com/owncloud/owncloud-design-system/issues/762

Would be good to use the `OcSelect` now for the `OcAutocomplete` component internally as well.

Right now the `OcAutocomplete` component works with an input element for searching and a uikit `uk-drop` for the dropdown holding the items. The `OcSelect` component already brings along all of that. An example usage of the `OcSelect` component can be found here: https://github.com/owncloud/web/blob/8a2284fb7a0c8c3564874b72ec363d5c4773fe07/packages/web-app-files/src/components/Collaborators/CollaboratorsEditOptions.vue#L4

**Comment by kulmann** [comment]
Positive side effect of this is, that we'd get rid of one more usage of UIkit.

**Comment by pascalwengerter** [comment]
Closing this since we've deprecated the OcAutocomplete and will drop it in the future
