### ISSUE TITLE
Tooltips are being hidden under different content

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/owncloud-design-system#1321]
Saw this in `OcFilesTable` component

![Screenshot 2021-05-24 at 16 48 16](https://user-images.githubusercontent.com/25989331/119365171-f6bfdd80-bcaf-11eb-997c-ab91159940ff.png)

**Comment by pascalwengerter** [comment]
Can confirm this, maybe we can manage to fix this & include it in `7.0.0`?

**Comment by pascalwengerter** [comment]
Found this one which may explain why it doesn't work in the files table: https://stackoverflow.com/questions/62405564/tippy-js-z-index-not-working-with-interactivity

**Comment by kulmann** [comment]
Disabling `interactive` since it is causing this behaviour and we don't need it. PR incoming.
