### ISSUE TITLE
Missing a useful icon - "check" aka "tick" aka "approve" aka "confirm"

### ISSUE THREAD

**Issue by rpocklin** [owncloud/owncloud-design-system#1341]
We would like to use a ✔️ style icon from this library, but cannot find one suitable here: https://owncloud.design/#/Design%20Tokens/Icon

Think of it as the inverse of the "close" ❌ icon which is present.

I can see a corresponding one in the base UI Kit here: https://getuikit.com/docs/icon (called "check") is it possible to add this?

Not sure of the complexity of raising this as a PR, happy to explore this option also but might be an easy one for you guys to facilitate.

**Comment by kulmann** [comment]
We have the `ready` icon (see screenshot). I suppose you'd like to have one without the circle, right? 😃 

<img width="318" alt="Screenshot 2021-06-01 at 09 32 51" src="https://user-images.githubusercontent.com/3532843/120284282-63446900-c2bc-11eb-8014-0595524d50f6.png">

**Comment by rpocklin** [comment]
Yep, without the circle is what we are after :)

**Comment by pascalwengerter** [comment]
I'll have to do another ODS release today, maybe I can sneak the button/tick SVG in there as well!

**Comment by rpocklin** [comment]
I see it, thanks that was really quick to add =)
