### ISSUE TITLE
Discussion: Rearrange CI steps

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/owncloud-design-system#1357]
### Expected behaviour
CI should fail as early as possible

### Actual behaviour
Unit tests are run as the last step, after building the docs & package. From my understanding that order isn't necessary, but maybe I'm mistaken?

### Screenshots

<img width="142" alt="Screenshot 2021-06-07 at 16 54 00" src="https://user-images.githubusercontent.com/16822008/121051089-11ff1280-c7b1-11eb-8479-e582185e5a28.png">

**Comment by kulmann** [comment]
Additionally we now have the `Sonarcloud` pipeline. IMO some pipelines can run in parallel, to speed things up.

**Comment by phil-davis** [comment]
ToDo:
- see which steps are really dependent on each other
- split into a couple of pipelines, as long as that reduces overall run-time
- do "dumb-easy" checks as early as possible (e.g. lint) so that a pipeline will fail early if those sort of checks are failing

**Comment by pascalwengerter** [comment]
Hey @dpakach, thanks for taking care of this! From what I see in the last CI run this doesn't implement the idea I had in mind when writing the ticket though 😉 

What I originally wanted was to re-arrange steps so the "costly" build steps happen _after_ linting and tests have passed successfully. 

A rough idea was to have the following order:

- Clone
- Dependencies
- eslint
- stylelint
- unit tests
- sonarcloud
- build docs
- build system
- changelog/publish

How many steps this is separated into is kinda up to you

**Comment by kulmann** [comment]
There are some things that can be parallelized, like e.g. `build docs` and `build system` can run in parallel. But those should only start if all the cheaper/easier steps were successful, like @pascalwengerter already explained.

**Comment by dpakach** [comment]
@pascalwengerter  that sounds good too, I just thought that if we separate into different pipeline, we can just run the testing+linting and build pipelines in parallel which will also save a minute or two.
I dont think we can run the drone steps in parallel. There is a option for `detach` which can be set so that the steps behave like services. But the detached steps dont fail the build.

https://docs.drone.io/pipeline/exec/syntax/steps/#detach

**Comment by kulmann** [comment]
Sorry, what I meant was having `build docs` and `build system` in their own pipelines respectively, and then let them depend on whatever makes sense to run before (the `cheap` pipelines)

**Comment by pascalwengerter** [comment]
> @pascalwengerter that sounds good too, I just thought that if we separate into different pipeline, we can just run the testing+linting and build pipelines in parallel which will also save a minute or two.
> I dont think we can run the drone steps in parallel. There is a option for `detach` which can be set so that the steps behave like services. But the detached steps dont fail the build.
> 
> https://docs.drone.io/pipeline/exec/syntax/steps/#detach

No need to get too funky here from my POV, all I wanted was run the 20s unit-test step a bit earlier for quicker feedback :) everything else is a plus but no must

**Comment by dpakach** [comment]
Looks like I was wrong earlier 😅 , It seems to be possible to run the steps in a pipeline in parallel. I changed it the way as @pascalwengerter suggested and seems like the build is faster than earlier.
https://drone.owncloud.com/owncloud/owncloud-design-system/3138

**Comment by pascalwengerter** [comment]
Pipelines doesn't stop when unit tests fail

![Screenshot 2021-07-01 at 10-07-36 Build #3234 1 5 - owncloud owncloud-design-system - Drone CI](https://user-images.githubusercontent.com/16822008/124098133-2eab0500-da54-11eb-9f2a-c25d9ee62807.png)

**Comment by phil-davis** [comment]
@dpakach can you take a look.

From memory, you might have managed to get all 3 "unit tests", "build docs" and "build system" steps running at the same time. If that is so, then when the unit tests fail, the other steps are already running. It might be harder to stop them?

**Comment by pascalwengerter** [comment]
Please only start the build steps after the unit tests have passed, as stated above

**Comment by dpakach** [comment]
@pascalwengerter fixed it in https://github.com/owncloud/owncloud-design-system/pull/1456
please review
