### ISSUE TITLE
OcTableFiles: Sorting is no working by clicking on "Share owner" column header

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/owncloud-design-system#1370]
### Steps to reproduce
1. Click on the header "Share owner"

### Expected behaviour
The table is sorted in alphabetical ascending or (by the second click) descending order by share owner's surname as the the default user icons also show the first letter of the surname

### Actual behaviour
Clicking has no effect

**Comment by elizavetaRa** [comment]
@pascalwengerter I updated the issue template, I would expect sorting by the surname

**Comment by pascalwengerter** [comment]
> @pascalwengerter I updated the issue template, I would expect sorting by the surname

Thanks! A fix for this is in the making ✌🏽 we'll sort by by `displayName` attribute, which usually is {{surname lastname}} and will sort accordingly
