### ISSUE TITLE
Add small border between active/hovered route items in OcSidebarNav

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/owncloud-design-system#1387]
### Steps to reproduce
1. Check OcSidebarNav
2. Hover over the item next to the current active route

### Expected behaviour
Small border between the two links (according to @ChrisEdS, thanks for the hint)

### Actual behaviour
No border, both items look like they "unite"

### Screenshots (if appropriate):
![Clipboard - 10  Juni 2021 18 13](https://user-images.githubusercontent.com/16822008/122194184-1dc39680-ce8d-11eb-83bf-77866285d993.png)

**Comment by kulmann** [comment]
Makes sense. We have a `border-left` and `border-right` at the moment. Would simply need to be changed to `border` so that it applies to all edges. CSS lives in `OcSidebarNavItem.vue`. Worth a try if this looks good.

**Comment by pascalwengerter** [comment]
Looks a bit better IMO but there's still something about it somehow.

Opinions @tbsbdr @kulmann @ChrisEdS ? :)

<img width="412" alt="Screenshot 2021-06-16 at 12 32 20" src="https://user-images.githubusercontent.com/16822008/122211704-ecec5d00-ce9e-11eb-8d8b-b75cc790bc2e.png">

**Comment by kulmann** [comment]
Visible borders doubling into 2px. That looks weird. Could you try only setting the left, right and bottom border?

**Comment by pascalwengerter** [comment]
Way better

<img width="412" alt="Screenshot 2021-06-16 at 12 43 34" src="https://user-images.githubusercontent.com/16822008/122213109-810af400-cea0-11eb-89ab-054db3fb1fce.png">

**Comment by pascalwengerter** [comment]
Do I get executive permission to horizontally center the `made by ownClouders` text in the component as well? Haha

**Comment by ChrisEdS** [comment]
> Do I get executive permission to horizontally center the `made by ownClouders` text in the component as well? Haha

Make sense. Should the text be smaller as well? Looks very prominent.

**Comment by kulmann** [comment]
The text `Made by ownClouders` is only an example doc text. The sidebar has a slot for the `footer` content. Up to the developer to decide what happens there - in our case it's used in the `web-runtime`, i.e. the same for all extensions. Currently we don't show anything in the sidebar footer in web. You can change the example here @pascalwengerter, but please don't enforce styles on the footer. Meaning: please don't change the component, only the template for the `footer` slot in the docs examples.
