### ISSUE TITLE
apply owncloud css to new elements

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/owncloud-design-system#14]

**Comment by DeepDiver1975** [comment]
we should apply uikit classes - e.g. https://getuikit.com/docs/button

**Comment by scramb** [comment]
We should not use UiKit classes to design such simple styles as buttons; by using too many UiKit classes we simply failed to use vueds - UiKit does not use the DesignToken which is a basic part of the system. We really shouldn't be saving here and build reasonable components and styles right from the start that we can rely on in the long run.

**Comment by DeepDiver1975** [comment]
So you are saying we can use UiKit styles for pattern but not for elements?

I question is non-uikit elements are working in uikit-based patterns. We will see ....
At least the uikit styled buttons look :hankey:

**Comment by DeepDiver1975** [comment]
addressed in #34
