### ISSUE TITLE
OcTextArea: Add a way to enter a line break

### ISSUE THREAD

**Issue by dschmidt** [owncloud/owncloud-design-system#1422]
### Steps to reproduce
1. Type enter in OcTextArea
2. Change event is emitted and enter is swallowed

### Expected behaviour
There should be a way to enter a line break, maybe with ctrl+enter?

### Actual behaviour
There is no way to enter a line break ...

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by LukasHirt** [comment]
Let's go with combinations `ctrl + enter` and `shift + enter`

**Comment by kulmann** [comment]
To be honest I'm always annoyed when I use a textfield that submits on enter. I'd prefer to change it entirely and use `enter` for line breaks and fire a change event when leaving the textarea or pressing `ctrl + enter` or `shift + enter`.

**Comment by LukasHirt** [comment]
> I'd prefer to change it entirely and use enter for line breaks and fire a change event when leaving the textarea or pressing ctrl + enter or shift + enter.

I think this could be more harmful. At least definitely submitting on leave. If I see a comments section, fill in some text, click/focus away and suddenly it is submitted I am scratching my head what went wrong... Regarding line breaks on `enter` **only** - I'd say people will be more used to submitting it instead. If you type in a username and password and hit enter, you get logged in. If you are adding some item/people to some list, you enter name, hit enter and it's added. Suddenly you're in a text area where it's different. I know that text area and input are quite different but not sure how much users will differentiate between them. Also, I see this patter more often in websites/apps. And given especially how everything is rushed, it is much simpler to just submit a message via hitting enter only. So as long as it's not some text editor where you expect to do tens of line breaks, I think the focus is more on submitting which means it should be as easy as possible.

**Comment by dschmidt** [comment]
Fwiw OcTextInput emits changed on enter as well ...

**Comment by kulmann** [comment]
Since this is our design system, I'd think this screams `make <ENTER> behaviour configurable` all over the place. 😁 
For the `OcTextInput` I'd be confused if it doesn't do anything on enter. For the `OcTextArea` not. I mean, right now writing a comment on github, I expect that a simple `ENTER` creates a line break (you're right that that's a text editor). For chat I'd expect `ENTER` to submit my message.

**Comment by paulcod3** [comment]
OcTextArea will have an optional prop called `submitOnEnter`, this prop controls how the textarea should react to `ENTER`.
It will be set default to false, which means `ENTER` doesn't emit a change event. If its set to true `ENTER` will emit a change event, and `CTRL + ENTER` or `SHIFT + ENTER` will create a linebreak. This way the behaviour is configurable.

**Comment by dschmidt** [comment]
Is a change event emitted when the value changed and the focus is lost?

**Comment by paulcod3** [comment]
@dschmidt no not as of now, would that be a needed case?

**Comment by dschmidt** [comment]
Well, it's what `OcTextInput` does. So I kinda expect `OcTextArea` to behave similarly. 

See also https://github.com/owncloud/web/issues/8857
In that table I haven't recorded when the change event is emitted, that might still be interesting.

**Comment by paulcod3** [comment]
ok I will do an issue for that to fix it :)
