### ISSUE TITLE
OcSelect should use value property instead of model property

### ISSUE THREAD

**Issue by dschmidt** [owncloud/owncloud-design-system#1448]
### Expected behaviour
Use `:value` binding and see it works.

### Actual behaviour
1. Use `:value` binding
2. See it doesn't work
3. Feel confused
4. Check vue-select documentation
5. See it's using `value` prop
6. Feel more confused
7. Look at OcSelect
8. Find out that it uses `model` as property for whatever reason

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by dschmidt** [comment]
@LukasHirt is there a reason you introduced the model property instead of value in the first place?

**Comment by LukasHirt** [comment]
> is there a reason you introduced the model property instead of value in the first place?

I used it as `model` is the recommended way how to handle inputs. Binding value would require us to handle the change manually not to get mutation error. We can still use `value` as a prop for the model though so that would already be an improvement and would satisfy both use cases
