### ISSUE TITLE
OcSwitch: state is (visually) not clear

### ISSUE THREAD

**Issue by kulmann** [owncloud/owncloud-design-system#1457]
### Steps to reproduce
1. Trigger the OcSwitch, e.g. as used in the `Show hidden files` in ownCloud Web 

### Expected behaviour
Immediately know if the state is `on` or `off`

### Actual behaviour
Not so sure about the state. The position of the switch (left or right) gives a good hint. But the colors of the `on` and `off` state are pretty similar.

### Screenshots (if appropriate):
<img width="187" alt="Screenshot 2021-07-01 at 16 55 21" src="https://user-images.githubusercontent.com/3532843/124146097-b8c38f80-da8d-11eb-8afb-ee14ba79983a.png">
<img width="187" alt="Screenshot 2021-07-01 at 16 55 26" src="https://user-images.githubusercontent.com/3532843/124146104-b9f4bc80-da8d-11eb-9986-1b9a2f9e124d.png">

**Comment by paulcod3** [comment]
@kulmann 
![turned on](https://user-images.githubusercontent.com/786551/126345069-797e179f-7342-4dd4-8a1f-27d21efc3a5c.png)
![turned off](https://user-images.githubusercontent.com/786551/126345076-fcddf108-fee3-435b-b432-60e78cd54bf5.png)
How about a red color for the disabled state and the ownCloud dark color for enabled?

**Comment by LukasHirt** [comment]
> How about a red color for the disabled state

My feeling would be that disabling it would lead to some dangerous action...

**Comment by paulcod3** [comment]
yes that could be true

**Comment by paulcod3** [comment]
Ok we stayed with a more neutral color when disabled, as can be seen in the PR
