### ISSUE TITLE
[Bug] "sort by modified date" shows mixed order

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/owncloud-design-system#1552]
### Steps to reproduce
1. login to web.owncloud.com
2. sort files by "modified"
3. see mixed dates in modified column

https://user-images.githubusercontent.com/26610733/127339747-434b14e5-766a-40ad-8b94-150f030e5501.mp4

### Expected behaviour
sort files by modified-date

**Comment by pascalwengerter** [comment]
Could reproduce this on [owncloud.design](https://owncloud.design/#/oC%20Components/OcTableFiles) by setting the examples' mdates to the following

```js
// 1st
mdate: "Sun, 25 Jul 2021 14:27:13 GMT",

// 2nd
mdate: "Mon, 31 Aug 2020 09:19:03 GMT",

// 3rd
mdate: "Mon, 26 Jul 2021 08:16:18 GMT",
```
