### ISSUE TITLE
Make DatePicker accept theme colors

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/owncloud-design-system#1679]
We recently changed the underlying library for our DatePicker

### Expected behaviour
It should respect theme colors

### Actual behaviour
It does currently not respect theme colors (regression)

**Comment by kulmann** [comment]
There was some theming related css in https://github.com/owncloud/owncloud-design-system/pull/1183/files - need to check in details if that's sufficient.

**Comment by pascalwengerter** [comment]
Fixed via #1740
