### ISSUE TITLE
Truncate filename instead of file extension

### ISSUE THREAD

**Issue by kulmann** [owncloud/owncloud-design-system#1758]
### Steps to reproduce
1. Have a file with a long filename, e.g. `very-long-file-name-with-too-much-content.txt`
2. Have a small screen resolution, e.g. tablet in portrait mode

### Expected behaviour
Parts of the filename should be truncated, e.g. `very-long-file-nam…ontent.txt`

### Actual behaviour
The end of the filename gets truncated, including the file extension, e.g. `very-long-file-name-with-to…`

**Comment by pascalwengerter** [comment]
@kulmann @JammingBen can this be closed since #1782 got merged?

**Comment by kulmann** [comment]
Yes, thanks 👍
