### ISSUE TITLE
Checkboxes lack focus border

### ISSUE THREAD

**Issue by kulmann** [owncloud/owncloud-design-system#1961]
### Steps to reproduce
1. Have an OcCheckbox on screen (design docs or oC Web)
2. Use your keyboard `TAB` key to cycle through UI controls
3. Reach the OcCheckbox

### Expected behaviour
I should have a clear visual guidance of what element currently has the keyboard focus

### Actual behaviour
The OcCheckbox doesn't have any focus border/highlighting anymore

**Comment by dschmidt** [comment]
more specific version of https://github.com/owncloud/owncloud-design-system/issues/445
possibly duplicate but also easier to solve/close, so not sure.

**Comment by kulmann** [comment]
Checkboxes do have a focus border, so apparently fixed in the meantime. @lookacat was working on it. Closing here.

The other issue that you linked is more general about the focus border styling. Which still can and should be improved according to our recent audit. 😞

**Comment by lookacat** [comment]
nice, i accidentally fixed an issue instead of creating one :D

**Comment by kulmann** [comment]
> nice, i accidentally fixed an issue instead of creating one :D?

As far as I remember this was on purpose by you :-P

**Comment by lookacat** [comment]
yes. purpose.
