### ISSUE TITLE
ocTable: strange column header alignment when sortable

### ISSUE THREAD

**Issue by diocas** [owncloud/owncloud-design-system#2118]
When a column header on ocTable is sortable but is not active, the sort arrow has `oc-invisible`. The issue here is that the text no longer aligns with the row's text, which doesn't look good.

Maybe the element could be removed (maybe it needs to ensure we keep the arrow size to the left of the element, to avoid having the columns re-sizing).

![image](https://user-images.githubusercontent.com/2589871/166256955-07e5dba4-0e9b-487f-80d5-db7badd648bf.png)

**Comment by elizavetaRa** [comment]
the same issue as https://github.com/owncloud/owncloud-design-system/issues/2028
