### ISSUE TITLE
Typo in repo labels

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/owncloud-design-system#2336]
### Expected behaviour
Guess it should be `vuejs` insteadt of `vueds`? :)

### Actual behaviour
![Screenshot 2022-10-04 at 19-46-34 owncloud_owncloud-design-system A pattern library for ownCloud for Vue js](https://user-images.githubusercontent.com/16822008/193889554-1dacf8ac-ee69-45e8-aec0-dbd564a1a6b7.png)

**Comment by kulmann** [comment]
https://vueds.com/ 😁

**Comment by pascalwengerter** [comment]
> https://vueds.com/ 😁

Meeeeh thx 😅
