### ISSUE TITLE
secondary nav bar

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/owncloud-design-system#235]
as discussed some time back:
we need a better component for the secondary nav bar

## Requirements
- [ ] allow responsive behavior
- [ ] introduce this as new component - we will delete oc-top-bar later after the transition
- [ ] use slots to place elements inside the nav bar

**Comment by felixheidecke** [comment]
You mean … the "app-bar" ?

**Comment by DeepDiver1975** [comment]
> You mean … the "app-bar" ?

according to https://github.com/owncloud/owncloud-design-system/issues/239 - yes 'app-bar'

**Comment by DeepDiver1975** [comment]
will be addressed in #323
