### ISSUE TITLE
Naming things

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/owncloud-design-system#239]
As "naming things" was driving me crazy, I hereby propose these names for these sections:

![pnx_naming_things](https://user-images.githubusercontent.com/12717530/57769409-1958ac80-770e-11e9-83cd-cfca7ca3c04e.png)

Feel free to comment and improve :+1:

**Comment by felixheidecke** [comment]
If we all can agree on these names, I'll go ahead and start giving away individual selectors. I'm currently thinking about how to differentiate between reusable components `.oc-checkbox` and `.oc-avatar` etc. and individual, single-purpose implementations like `.$_phoenix_topbar` and `.$_appname_app-bar` so these can be targeted individually, even on an app-basis, as we do with computed properties in components already.

* `oc-name` = general styling (like navbar)
* `$_appname_name` = individual styting (like topbar)

to avoid collisions. Who is with me?

**Comment by LukasHirt** [comment]
Sounds good. 👍  Maybe I would change the general one to `$_oc_name` to keep it in the same style as the individual one and maybe show app developers that it would be nice to have it as a standard (I guess I'm kinda naive this would work - right?). But this is more like my personal preference so I'm fine with both ways.

**Comment by LukasHirt** [comment]
Also to the original issue and not the comment - IMHO would be maybe better to change `personal` to `user`. I would see `personal` more like some personal settings page or preview of profile. Then we could also discuss if these two are not already also some kind of apps.

**Comment by felixheidecke** [comment]
I agree with both change requests 😺👍

**Comment by DeepDiver1975** [comment]
Naming has been applied from my pov -> lose
