### ISSUE TITLE
Handling helper- and utility-classes

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/owncloud-design-system#240]
As I'm working on the grid element, I am heavily depending on the width and visibility classes.

Those classes are component agnostic and help with making them responsive, hide or display them and all that jazz. I'm mainly talking:

* [Width](https://getuikit.com/docs/width)
* [Flex](https://getuikit.com/docs/flex)
* [Visibility](https://getuikit.com/docs/visibility)
* [Utility](https://getuikit.com/docs/utility)

As well as things such as [sticky](https://getuikit.com/docs/sticky), [sortable](https://getuikit.com/docs/sortable), [scrollspy](https://getuikit.com/docs/scrollspy), and the like.

@DeepDiver1975 @LukasHirt I don't currently know how to make them available to developers without resorting back to the regular class system, but I need a solution quickly.

## Example

![visibility](https://user-images.githubusercontent.com/12717530/56656549-12ea8e00-6696-11e9-9eba-e5dfd3c6f0f8.png)

1. The wrapper for the search-bar (in this case a column in the grid) turns invisible in a small viewport
2. small search-bar is shown in medium viewports in the dropdown

We need the support for the existing components as well as any simple HTML tag (div, span, etc.)

**Comment by LukasHirt** [comment]
And would it be a problem if you'd continue using the regular class system?

**Comment by DeepDiver1975** [comment]
Well for anything which does not need to be controlled from the application code (javacript) I'm fine in using css class as is. Anything which needs to be controlled from the application logic needs props.

So I'm absolutly fine in using the proposed solution on top.
(While I sitill would like to see these classes to be named oc-card oc-hidden and so one - just from a cosmetics point of view)

**Comment by felixheidecke** [comment]
> And would it be a problem if you'd continue using the regular class system?

Works fine with the regular approach.
