### ISSUE TITLE
disabled buttons have a hover effect ...

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/owncloud-design-system#272]
feels strange - no idea if intended

@felixheidecke can you comment pelase?

THX

**Comment by DeepDiver1975** [comment]
@felixheidecke :wave:

**Comment by LukasHirt** [comment]
This is wrong. Needs to be prevented.

**Comment by felixheidecke** [comment]
No, it's definitely not intended and "usually" uikit doesn't do that. Let's see where the bug comes from.
