### ISSUE TITLE
Select component

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/owncloud-design-system#279]
## Description
We need a select component. I would prefer to use drop which would have same styles as autocomplete but would be triggered by button, link, etc.

**Comment by DeepDiver1975** [comment]
Oc-autocomplete could work dir this purpose. Or am i Missing anything?

**Comment by LukasHirt** [comment]
Yes, it can be used but it would need to be adjusted.

**Comment by LukasHirt** [comment]
Reopening since it is again needed. I'll provide more description.

**Comment by felixheidecke** [comment]
```html
<select v-model="myData" class="uk-select">
    <option></option>
    <option></option>
</select>
```

Does that already do the trick? @LukasHirt

**Comment by LukasHirt** [comment]
It styles only the input. I need also the options...

We need to make a drop with same styles as autocomplete drop accessible even without autocomplete input (e. g. instead of input button). Most of that can be achieved simply by using same classes but there are some "bugs" - no hover effect, not closing after a click.

![image](https://user-images.githubusercontent.com/25989331/60593583-5f8fcb00-9da3-11e9-93f6-b88ef910ccc5.png)

**Comment by felixheidecke** [comment]
I can put that on my agenda.

**Comment by LukasHirt** [comment]
Added option to close drop after click (#414) so this is not really needed anymore since we can build it simply with drop and autocomplete classes - closing.
