### ISSUE TITLE
Identifying, theming and testing in Phoenix

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/owncloud-design-system#284]
As discussed with @DeepDiver1975, we are faced with the following challenges:

**Theming and testing templates, pages, and context-specific components, that don't and/or shouldn't exist in ODS**

Such as:
* The file-list (table in app-context)
* Files-action button row in file-list (button row in component-context)
* The login (single purpose page)
* The files-sidebar (app-context)

Sub-Components are being built in the context of applications and may require special styling via a unique selector. _(also needed for testing purposes btw.)_

## Motivation:

* Distinction between Elements/Patterns, components and apps
* Prevent naming collisions
* Create propper CSS specificity-order for Layouting/Styling
* Create readable and comprehensible selectors for testing
* Create a convention to work with ;-)

### 1.) Reusable Elements and Patterns (Phoenix base)

Reusable element and pattern are to classified as follows:

`<div class="oc-element">[…]</div>`

these classes can be extended in variations

`<div class="oc-element oc-element-variation">[…]</div>`

to be set as the class name sequence if so desired

Examples are:

* `.oc-button`
* `.oc-checkbox`
* `.oc-breadcrumb`
* …

### 2.) Single purpose components (Phoenix base)

Components build from elements and patterns and/or arbitrary HTML that occur no more that once are to be identified as follows:

`<section id="oc-component">[…]</section>`

Examples are:

* `#oc-topbar`
* `#oc-menu`
* `#oc-app-container`
* ...

Allows encased selectors with higher specificity:

```scss
#oc-topbar {
  .oc-element {}
}
```

### 3.) Applications

Applications hold the app_id in it's outer most wrapper, so all contents can be addressed in the app context.

`<main id="files">[…]</main>`

Subsequent subcomponents are to be identified and prefixed as described in 2.

`<oc-table id="files-filelist">[…]`
`<aside id="files-sidebar" />`

Classes within applications are to be privatised starting with a low dash.

```html
<div id="files">
  <oc-table id="files-filelist">
    <oc-table-row class="_filelist_actions-row">[…]</oc-table-row>
  </oc-table>
</div>
```

Allows encased selectors with higher specificity and provides readable selectors:

```scss
#files {
  // components
  &-appbar {}
  &-filelist {}

  // private classes
  ._ {
    &filelist-action-row {}
  }
}
```

### Template example

```html
<div id="Phoenix">
    <div id="oc-notifications">
        <div class="oc-notification">1</div>
        <div class="oc-notification">2</div>
        <div class="oc-notification">3</div>
    </div>
    <header id="oc-topbar"></header>
    <nav id="oc-menu"></nav>
    <div id="oc-app-container">
        <div id="files">
            <oc-appbar is="header" id="files-appbar"></oc-app-bar>
            <oc-grid>
                <main id="files-file-list" class="uk-width-4-5@m"></main>
                <aside id="files-sidebar" class="uk-width-1-5@m"></aside>
            </oc-grid>
        </div>
    </div>
</div>
```

**Comment by felixheidecke** [comment]
This extends: https://github.com/owncloud/owncloud-design-system/issues/239

**Comment by felixheidecke** [comment]
## Themes and color pallets

![themes-color-pallets](https://user-images.githubusercontent.com/12717530/57786429-c1cd3780-7733-11e9-941e-809b086aaac8.png)

**Want to change colors in the default theme?**
Go have fun with the design tokens

**Want to create a peruvian theme?**
Go have fun with Sass :-)

**Comment by felixheidecke** [comment]
Why classes and IDs?

HTML intends to use classes on elements that do appear _more than once on a single page_. Ids are only allowed once per page.

Using classes and IDs in the context [set here](https://github.com/owncloud/owncloud-design-system/issues/284#issue-444482115) follows the w3c rules for HTML Markup.


🔴 **Invalid HTML**
```html
<div id="app">
   <button id="button" />
   <button id="button" />
</div>
```

💚 **Valid HTML**
```html
<div id="app">
   <button class="button" />
   <button class="button" />
</div>
```

**Comment by DeepDiver1975** [comment]
Since theming and stuff is out of scope for now -> close.

Once we get proper requirements we will think about solutions
