### ISSUE TITLE
[IE11-QA] Cross icon displayed twice in the search box

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/owncloud-design-system#327]
Steps to recreate:
1) Start typing into the search box

Expected result: One cross icon to delete the input
Actual result: Two cross icons

![image](https://user-images.githubusercontent.com/49001702/58945568-6287a380-8784-11e9-9916-b43d0f14e7ba.png)

**Comment by felixheidecke** [comment]
IE and Edge add their own clear buttons. But this can be overwritten. Will do.

**Comment by DeepDiver1975** [comment]
still needs fixing - @felixheidecke code changes need to be applied ....
