### ISSUE TITLE
oc-icon clickable

### ISSUE THREAD

**Issue by Julian1998** [owncloud/owncloud-design-system#352]
A 'clickable' (changes cursor to pointer) prop for the oc-icon element which allows you to simulate the icon as button would be lovely :)

Needed for example in https://github.com/owncloud/phoenix/pull/1205

**Comment by DeepDiver1975** [comment]
@felixheidecke please have a look - thx

**Comment by felixheidecke** [comment]
@Julian1998 after merging https://github.com/owncloud/owncloud-design-system/pull/358, just add this class and you're good to go.

**Comment by Julian1998** [comment]
@felixheidecke Thanks a lot! What about adding a clickable prop to the icon component additionally? Using the new helper class :)

**Comment by felixheidecke** [comment]
@Julian1998 I guess the prop would just be a different way of adding the class right?

`<[…] :class="{ 'oc-cursor-pointer' : this.clickable }" />`

**Comment by DeepDiver1975** [comment]
developers want to control any aspect of the frontend by using javascript. This is where this request is coming from and boils down to my very initial design requirement of ODS .... which got lost down the road ... :man_shrugging:
