### ISSUE TITLE
oc-drop should accept offsets

### ISSUE THREAD

**Issue by Julian1998** [owncloud/owncloud-design-system#380]
![Bildschirmfoto von »2019-06-28 20-49-03«](https://user-images.githubusercontent.com/2546997/60364384-4f17d300-99e6-11e9-99ae-39116d793c14.png)

As you can see, supporting the uk offset attributes in an oc-drop element would be very helpful :)
https://getuikit.com/docs/drop#offset

**Comment by LukasHirt** [comment]
You can actually do it with options prop - `:options="{ 'offset': '0' }"`. But yes, it would be nice to have it with its own prop.

**Comment by Julian1998** [comment]
> You can actually do it with options prop - `:options="{ 'offset': '0' }"`. But yes, it would be nice to have it with its own prop.

Exactly. That's why I labelled it as question and enhancement

**Comment by pascalwengerter** [comment]
Closed as stale/outdated
