### ISSUE TITLE
Date type input

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/owncloud-design-system#393]
## Description
We need input with type date that allows us to either write the date or select it with the date picker.

**Comment by LukasHirt** [comment]
@felixheidecke Do you have already too much tasks to do now or can you take this one as well?

**Comment by DeepDiver1975** [comment]
let's just reuse what is available out there - https://github.com/charliekassel/vuejs-datepicker

it has the highest rating on https://madewithvuejs.com/blog/best-vue-js-datepickers

**Comment by felixheidecke** [comment]
Sounds good. But we should drop the styles present and use our own styles:
https://github.com/charliekassel/vuejs-datepicker/blob/master/src/styles/style.styl

**Comment by LukasHirt** [comment]
Check pls if you can write the date in that component manually - this is one of the requirements.

**Comment by DeepDiver1975** [comment]
> Check pls if you can write the date in that component manually - this is one of the requirements.

there is a properly 'typeable' - https://github.com/charliekassel/vuejs-datepicker/blob/master/README.md

**Comment by LukasHirt** [comment]
Perfect! Thanks a lot! I just went through demos so far and haven't seen it there as an example 😁

**Comment by LukasHirt** [comment]
Taken care of in #467 - closing
