### ISSUE TITLE
Spinner is not animated in ie11

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/owncloud-design-system#423]
## Description
The svg animations are not supported in ie11 thus the spinner from uikit won't work there.

**Comment by felixheidecke** [comment]
So I guess we just build an extra IE11 fallback based on a GIF?!

**Comment by LukasHirt** [comment]
Other option could be using only a simple transition - not animating how the spinner gets filled but only have it filled a little bit all the time and gave it a rotation. Simply done without UIkit.
