### ISSUE TITLE
Avoid usage of uppercase

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/owncloud-design-system#442]
## Description
Some screen readers will read these labels as abbreviations: "M.E.N.U." etc. E. g. buttons

**Comment by felixheidecke** [comment]
Does that happen somewhere?

**Comment by LukasHirt** [comment]
Yes.

> E. g. buttons

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/owncloud-design-system/pull/652
