### ISSUE TITLE
Missing oc-table

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud-design-system#480]
`oc-table` is [being used in Phoenix](https://github.com/owncloud/phoenix/blob/master/apps/files/src/components/FileList.vue#L5) but its documentation is not appearing in the design system.

**Comment by LukasHirt** [comment]
There is this page - https://owncloud.github.io/owncloud-design-system/#/Patterns/oc-table or do I get the issue wrong?

**Comment by PVince81** [comment]
Weird... I often have trouble finding elements in that navigation for some reason
