### ISSUE TITLE
Switch element state difficult to read

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud-design-system#482]
Visually, the switch is not quickly readable, especially when there are multiple ones in a row:
<img width="437" alt="image" src="https://user-images.githubusercontent.com/277525/64784265-07770100-d56a-11e9-8ec0-a42af1fc8a88.png">

Look at the above and try to quickly assess what is enabled and what is not.

Now compare this to regular checkboxes:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/277525/64784378-4f962380-d56a-11e9-9b8f-df1c037396c6.png">

Which one of the two did you manage to assess faster ?

If we want to keep the switches, we need to make their enabled state more apparent like increasing the contrast (general [ticket about contrast](https://github.com/owncloud/owncloud-design-system/issues/444)), or change the layout of the permissions row to have the switches ordered in a way that is easier on the eye.

Thoughts ? @LukasHirt

**Comment by LukasHirt** [comment]
I agree with dropping them in collaborators. However, we still need to figure out how to improve the switch component since it is definitely going to be needed later.

**Comment by PVince81** [comment]
are there existing plans for using it that prevent us deleting it completely ?

**Comment by LukasHirt** [comment]
It's not good to use checkboxes every time. In some cases when the option is to switch something on or off and it doesn't need any confirmation like "Confirm", "Save" or "Ok" buttons then it's better to actually use switch instead.

**Comment by PVince81** [comment]
I could imagine such scenarios. Yes, I agree to use the switch in scenarios with immediate action with no saving needed, like toggling a mode for views.

**Comment by DeepDiver1975** [comment]
and switches can look good and behave intuitive

https://vuetifyjs.com/en/components/selection-controls#switches-states

**Comment by PVince81** [comment]
Indeed, the vuetify switches look nice!

**Comment by wuenschedesign** [comment]
If the handler of the toggle switch is rounded (instead of a square) it becomes easier to identify the handler and in which state the handler is. iOS toggle switches use green for selected state. Currently I am in favour of using action blue to make it consistent in the whole application, but no strong opinion though.

![Toggle-Switch](https://user-images.githubusercontent.com/40062503/70241431-51d5db80-176f-11ea-9712-a7e6f821881a.png)

**Comment by PVince81** [comment]
I believe we're not using the switches any more currently

**Comment by pascalwengerter** [comment]
Resolved in #1522
