### ISSUE TITLE
oc-icon should switch mouse cursor into pointer

### ISSUE THREAD

**Issue by VicDeo** [owncloud/owncloud-design-system#488]
...when oc-icon contains a click handler

**Comment by PVince81** [comment]
@marcus-herrmann would that make sense or should the responsibility be on the enclosing element maybe ? Slightly related to the oc-star discussion

**Comment by pascalwengerter** [comment]
Initial statement is only applicable if the icon is an interactive element, which we handle by wrapping it inside a button. For an example see e.g the [button docs](https://owncloud.design/#/oC%20Components/OcButton)
