### ISSUE TITLE
Run the unit tests on CI

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud-design-system#489]
- [x] enable unit tests run on CI, see https://github.com/owncloud/owncloud-design-system/tree/master/test/unit
- [ ] adjust PR template to ask developers for unit tests for the components

@LukasHirt as discussed, since some components have more complex logic

@DeepDiver1975

**Comment by LukasHirt** [comment]
Closing this and moving the remaining test into this ticket #508
