### ISSUE TITLE
Drop native tag attributes from component properties

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/owncloud-design-system#51]
@DeepDiver1975 @tempelgogo @scramb I am raising the idea if we can get rid of native attributes such as type, href and the like.

https://github.com/owncloud/owncloud-design-system/blob/pure-uikit/src/elements/OcButton.vue#L4

These attributes will work without having them as a props in the component and they don't receive additional validation. These props are … in essence … not doing anything at all ;-) What do you think?

**Comment by DeepDiver1975** [comment]
properties add features like default values, type and validators - so they have a benefit over native attributes.
in addition: we usually wrap elements and direct access to inner elements and their attributes is not possible.

i think using props is the right way to go in any case.

note on the side:
we need to keep the vue paradigm in mind: props down and events up!
