### ISSUE TITLE
Pencil icon not suitable for rename operations

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud-design-system#515]
What icon to use ?

@wuenschedesign

**Comment by LukasHirt** [comment]
Does this need a quick replacement? Could it wait until we have our "ownCloud icons" set done?

**Comment by DeepDiver1975** [comment]
1. choose one from https://material.io/resources/icons/?style=baseline
2. add it to ods
3. change the icon name in phoenix

alternative: define a proper name in ods and use this one - generally speaking we use the material names in ods ...

**Comment by wuenschedesign** [comment]
I suggest the following style for icons that distinguish between: Compose, Edit, Rename:

![Create-Edit-Rename](https://user-images.githubusercontent.com/40062503/70237881-5fd42e00-1768-11ea-98ff-80ddbf273302.png)

**Comment by pascalwengerter** [comment]
Fixed this a while ago by using the `edit` icon from https://owncloud.design/#/Design%20Tokens/Icon
