### ISSUE TITLE
File list components

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud-design-system#516]
Responsible for:
- rendering bulk actions including checkbox logic
- rendering file list from an array
- rendering column labels and their contents
- handling "empty content" scenarios
- handling "loading" scenarios
- handling filter scenarios
- ...

See https://github.com/owncloud/phoenix/issues/2077#issuecomment-542197139 for an example

**Comment by PVince81** [comment]
whether to also include a generic sidebar ? so far the current file list layout seems to be very dependent on whether the sidebar is open or not

**Comment by PVince81** [comment]
also note that at some point in the future the components could have a thumbnail view, in which it would not look like a list any more but still receive the same input properties, so that file actions and selection are still available.

this could for example be achieved by having a property that specifies the view type that we want.
or if this is too complex then we'd need another view.

Somehow this reminds me of any generic operating system listing component which has multiple view modes (icon, small icons, detailed list) which can be used not only for files but any kind of components with thumbnails. See for example Windows Explorer and also the view you get when you go to the control panel. Here we probably don't need to go that far though.

**Comment by DeepDiver1975** [comment]
As discussed today: we can have the layout and basic behavior of complex components in ODS - but using inheritance we can bring in additional functionality.

We did have issues with complex components in ODS when using them in phoenix - needs a second closer look.

**Comment by pascalwengerter** [comment]
@kulmann can we close this issue as outdated/too generic?

**Comment by kulmann** [comment]
Yes, the `OcTableFiles` component solves a lot of the mentioned ideas. Others have been kept in web, but might move over to ODS eventually. Anyway, I'd see this ticket here as solved.
