### ISSUE TITLE
Accessibility Docs & Improvements: OcDrop

### ISSUE THREAD

**Issue by marcus-herrmann** [owncloud/owncloud-design-system#518]
https://owncloud.github.io/owncloud-design-system/#/Elements/oc-drop

**Comment by marcus-herrmann** [comment]
See PR #522

**Comment by pascalwengerter** [comment]
@marcus-herrmann what was the goal of this issue? 🤓 I think we've resolved the accessibility concerns with OcDrop by now, so we can perhaps close this?

**Comment by marcus-herrmann** [comment]
@pascalwengerter It was way back in 2019 when there was the former interface present, and need for a disctinction between action menus and disclosure widgets. The new interfaces simplyfies this, and as you said, the issues around OcDrop seem to be resolved.
