### ISSUE TITLE
Document design guidelines

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud-design-system#537]
TODO: copy result of UX workshop here

**Comment by PVince81** [comment]
- [ ] accessibility: use tables and not divs to make tables
- [ ] button name must match action (ex: "Delete" instead of "OK")
- [ ] try to avoid modals as far as possible (check other solutions)
- [ ] decide on styling when folder / file or user is mentionned in sentences / prompts, etc (for example: bold or italic, quotes, ...)
   - [ ] => have a design system component with the styles
   - [ ] => could apply to emails as well
- [ ] always use text in icon buttons except for obvious cases (like a cross for closing)
- [ ] remove button or any controls instead of disabling whenever a feature is not accessible
- [ ] tone of voice, when to use "you" and "me" (open)
- [ ] to work on, how to display errors, validation, etc (open)

@marcus-herrmann above is the result of the workshop discussion
if you feel like some topics are too broad and need discussion, please raise a separate ticket for it and link in the checkbox row

**Comment by marcus-herrmann** [comment]
@PVince81 First draft: https://github.com/owncloud/owncloud-design-system/pull/542

**Comment by marcus-herrmann** [comment]
> @PVince81 First draft: #542

@PVince81 is this (#542) what you had in mind?

**Comment by pascalwengerter** [comment]
Closing this as party fixed / outdated / tracked elsewhere (e.g. #1193 )
