### ISSUE TITLE
Remove uikit

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud-design-system#538]
- [ ] Replace uikit classes with own ones where needed. For example: "uk-width-small" => "oc-width-small"
- [ ] Redefine uikit styles for now in "oc-" namespace (which can be adjusted later by a designer)
- [ ] Remove usage of uikit across Phoenix and make sure we have replacement "oc-" classes to use there if needed

@DeepDiver1975 @LukasHirt

**Comment by DeepDiver1975** [comment]
furthermore I'd welcome to use tags to define things like layout instead of having to append many classes. See vuetify ....
