### ISSUE TITLE
Autocomplete "no results" display is missing

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud-design-system#547]
### Steps

1. Use the share autocomplete in Phoenix
2. Type in a user name that does not exist

### Expected result
Dropdown opens, "Loading" appears in it, then a message "No results found" appears in the dropdown.

### Actual result
Dropdown opens, "Loading" appears in it, then the dropdown disappears again.
In some cases it's so fast that the dropdown doesn't even pop up, which gives the impression that it's broken / not working.

We should add a "No results" message.
The text should be configurable through properties to make sure we can translate them.

**Comment by pascalwengerter** [comment]
Closed as outdated since we'll remove the (now deprecated) OcAutocomplete component sometime soon
