### ISSUE TITLE
Autocomplete texts missing translation

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud-design-system#548]
I've spotted some texts that wouldn't be translatable because they are hard-coded in the autocomplete component: https://github.com/owncloud/owncloud-design-system/blob/master/src/patterns/OcAutocomplete.vue#L182

We should make all such texts configurable through properties, this way the caller can pass in a translated text.

**Comment by Julian1998** [comment]
@PVince81 passing them to the ods component is a good idea. Should we let the caller pass all texts which should get translated as one big object or each text on its own?

**Comment by Julian1998** [comment]
@PVince81 And I guess the caller should pass it already translated, right? As there is no possibility to translate in the ods I guess.
