### ISSUE TITLE
oc-icon shall optionally take a url from where to load the svg to be used

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/owncloud-design-system#562]
In some cases we need to display an icon as given to us by path - e.g. https://github.com/owncloud/phoenix/pull/2651/files#diff-9e4fc1110432e662806df44bc5b846a5R90

**Comment by PVince81** [comment]
I'll need this for the app switcher

**Comment by PVince81** [comment]
- Blocks https://github.com/owncloud/phoenix/issues/2650
- Blocks https://github.com/owncloud/phoenix/pull/2651
