### ISSUE TITLE
Avatar placeholder

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud-design-system#582]
When no URL is given or the URL failed to load, we should fall back to using a letter as an avatar placeholder.

We could have a look at https://github.com/eliep/vue-avatar

**Comment by DeepDiver1975** [comment]
used successfully - https://github.com/DeepDiver1975/turbo-eureka/blob/bbf0220ae177905b76b443028b51455adb60c64e/src/App.vue#L22
