### ISSUE TITLE
Further ideas for main navigation design

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud-design-system#583]
Moved from https://github.com/owncloud/phoenix/pull/2620#issuecomment-562607230 by @wuenschedesign 

### Screen shows that the Files application is opened
<img width="1440" alt="Top-Bar-Layout-01-List-View-A" src="https://user-images.githubusercontent.com/40062503/70332482-f6c0e900-1841-11ea-829a-72c0205daa40.png">

### Opened main navigation on the left side shows overview of all applications
<img width="1440" alt="Top-Bar-Layout-01-Applications-A" src="https://user-images.githubusercontent.com/40062503/70331901-b90f9080-1840-11ea-91a4-7ce15f9f567b.png">

### Account setting
<img width="1440" alt="Top-Bar-Layout-01-Account-Settings" src="https://user-images.githubusercontent.com/40062503/70332526-0b04e600-1842-11ea-80d4-d73f469e7750.png">

**Comment by pascalwengerter** [comment]
Closed as outdated, we'll update the navigation approach sometime soon (but differently)
