### ISSUE TITLE
Autocomplete dropdown doesn't close when fillOnSelection is false

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud-design-system#588]
Since the merge of https://github.com/owncloud/owncloud-design-system/pull/557, the autocomplete dropdown doesn't close when setting "fillOnSelection=false" as observed in https://github.com/owncloud/phoenix/pull/2727.

The following should be done:
- [x] add an example usage for `:fillOnSelection=false` inside the page for testing
- [x] fix the closing logic when `:fillOnSelection=false` (please note that this must be boolean, not string)
- [ ] fix the eslint warning about side effect, which might or might not be related: `../owncloud-design-system/src/patterns/OcAutocomplete.vue|228 col 10 error| Unexpected side effect in "$_ocAutocomplete_matches" computed property. (vue/no-side-effects-in-computed-properties) [vue/eslint]`

@marcus-herrmann please have a look if possible.
else I'll need to revert https://github.com/owncloud/owncloud-design-system/pull/557 in the meantime.

I had a look already but couldn't find what in your PR would cause this new issue

**Comment by DeepDiver1975** [comment]
The drop down is closed within the watcher on input. In case of fillOnSelection=false the input is not set and as a result the drop does not close.

**Comment by DeepDiver1975** [comment]
I did not touch the lint warning - need to understand why https://github.com/owncloud/owncloud-design-system/pull/557/files#diff-ad6944191fbfdde82283ccf6ff76fb29R226 was added 

@marcus-herrmann please let me know - THX

**Comment by PVince81** [comment]
fixed through https://github.com/owncloud/owncloud-design-system/pull/591
