### ISSUE TITLE
Fix top bar avatar

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud-design-system#596]
Since the introduction of vue-avatar there are some issues

- [ ] remove "width" attribute and replace with "size" and correct every usage
- [ ] in Phoenix, replace width/height with size as well
- [ ] adjust "files" app page to also use oc-avatar so we see how it looks like
- [ ] fix the style, alignment and sizes in the top bar for the avatar section
- [ ] same also in responsive mode

**Comment by pascalwengerter** [comment]
Closed as outdated, never heard anyone complain about the looks of the avatar in the top bar
