### ISSUE TITLE
oc-drop closeOnClick remove delay

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud-design-system#637]
We are calling UIKit's hide() function directly, which doesn't seem to be the intended usage.
Still, this is triggering a delay by default.

I suggest we follow what the documentation says and check the mode. If the mode is "click", then disable the delay by calling `.hide(false)`.

https://github.com/uikit/uikit/blob/develop/src/js/core/drop.js#L331

The workaround for users of oc-drop is currently to set "delayHide" to 0.

**Comment by PVince81** [comment]
also to investigate: why do we need `closeOnClick` logic in the first place ?

in Phoenix the oc-drop for file actions doesn't have it and clicking on an action automatically closes the dropdown. Maybe this was logic for an older version of UIKit ?

**Comment by pascalwengerter** [comment]
Closing this as not applicable anymore since @fschade replaced the `uk-drop` in `oc-drop` with `tippy` in #1269
