### ISSUE TITLE
Find a better place for coding guidelines for Phoenix and extensions

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud-design-system#642]
Currently we added https://github.com/owncloud/owncloud-design-system/pull/639 to ODS as it was the most common central place for Phoenix and extensions.

But it is not ideal as it refers to specific tools that might not be used in all extensions.

We should find a better structure for such documentation.
Maybe we need a higher level documentation that has sections, where one section is for ODS itself and other sections refer to various coding guidelines, extension docs, etc

**Comment by kulmann** [comment]
Will we provide some sort of app skeleton/template? In that case that would be a good place for dev docs.

**Comment by LukasHirt** [comment]
Dev docs have been implemented. Anything code related should live in there IMHO. Closing
