### ISSUE TITLE
Do not use pointer at active sidebar nav item

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/owncloud-design-system#693]
Since Vue doesn't allow navigation to current route, let's not use pointer there.

**Comment by pascalwengerter** [comment]
Can't reproduce, when hovering over the active nav item in web/oCIS it's not a clickable link/mouse is not displayed as pointer

**Comment by pascalwengerter** [comment]
Closing this as fixed, can't reproduce neither in ODS nor web
