### ISSUE TITLE
Use JSX for examples

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/owncloud-design-system#734]
Currently, we are using the Vue SFC syntax in the examples. What this results in are annoying errors. What would you say about using JSX instead for the examples so we don't see the error? The syntax is not that much different.

SFC:
![image](https://user-images.githubusercontent.com/25989331/80592165-42f20d00-8a1f-11ea-92ff-ad95532429cd.png)

JSX:
![image](https://user-images.githubusercontent.com/25989331/80592172-45ecfd80-8a1f-11ea-9edd-a153a56e4ee8.png)

What do you think @PVince81 @kulmann ?

**Comment by DeepDiver1975** [comment]
That's really nice - did not know this back when we kicked this off. Awesome!
