### ISSUE TITLE
Bring vue-select

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/owncloud-design-system#762]
We could replace our autocomplete component and create a select component with https://vue-select.org/ which already handles e.g. accessibility. We'd maybe make things easier for us then.

**Comment by LukasHirt** [comment]
Another good part - enables multiselection directly in the input field

![image](https://user-images.githubusercontent.com/25989331/81916533-3996a200-95d4-11ea-8d36-e8d733b72bed.png)

**Comment by kulmann** [comment]
Multiselect in OcAutocomplete would be awesome

**Comment by pascalwengerter** [comment]
@LukasHirt could you update this issue with your latest changes (perhaps a to-do list with components that should be migrated to vue-select later)? :)

**Comment by LukasHirt** [comment]
Closed in #1198
