### ISSUE TITLE
Optionally auto-close notifications

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/owncloud-design-system#766]
Currently, all notifications have to be closed manually. Even though this makes sense in a lot of use cases, some notifications do not really need to stay there until the user closes them.

Setting some prop like `auto-close="true"` would be very helpful.

**Comment by rpocklin** [comment]
@LukasHirt this would be really useful for our use-case, any plans to implement soon?  Would you accept a PR for this?

**Comment by LukasHirt** [comment]
@rpocklin It is not scheduled at the moment. If you'd like to tackle this, PR is always welcome :angel:
