### ISSUE TITLE
Do not include hidden section in the sidebar

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/owncloud-design-system#771]
E.g. private components. Still needs to be included in the final bundle though.

**Comment by pascalwengerter** [comment]
Don't really get what we're trying to achieve here. Is it about nav items in the docs or exporting certain components?

**Comment by LukasHirt** [comment]
Already resolved. We have a couple of hidden components that after one update started showing up in the sidebar. That's not the case anymore...
