### ISSUE TITLE
Button padding

### ISSUE THREAD

**Issue by kulmann** [owncloud/owncloud-design-system#777]
Buttons generally have quite large paddings on the left and right (see screenshot). Could be a bit more narrow. Is it intended like that or subject to change?
![Screenshot 2020-05-28 at 14 22 52](https://user-images.githubusercontent.com/3532843/83143418-3500dc00-a0f2-11ea-8905-527de2f0716b.png)
![Screenshot 2020-05-28 at 14 47 59](https://user-images.githubusercontent.com/3532843/83143435-3d591700-a0f2-11ea-83f1-0377d06571a7.png)

**Comment by LukasHirt** [comment]
AFAICT this is the default style from UIkit. Wouldn't see any problem with changing it.

**Comment by LukasHirt** [comment]
Done as part of #791
