### ISSUE TITLE
Logo in sidebar is quite small

### ISSUE THREAD

**Issue by kulmann** [owncloud/owncloud-design-system#795]
For me the logo in the left sidebar is quite small with it's 50px height. Fiddled around with the size and I would prefer 65px. Screenshots attached for comparison. Just my personal opinion, we should evaluate the logo size further, before we change it.

### logo with 50px height
![Screenshot 2020-06-16 at 11 23 35](https://user-images.githubusercontent.com/3532843/84757096-fe690380-afc3-11ea-97b8-8fd177ee62d5.png)

### logo with 65px height
![Screenshot 2020-06-16 at 11 14 08](https://user-images.githubusercontent.com/3532843/84757127-09bc2f00-afc4-11ea-9ace-22477b98c85f.png)

**Comment by pascalwengerter** [comment]
@kulmann has it been improved by #791 or is this still open?
