### ISSUE TITLE
Icons in buttons increase height by 1 Pixel

### ISSUE THREAD

**Issue by kulmann** [owncloud/owncloud-design-system#798]
When a button has an icon inside, the height gets increased by 1px. See screenshot (left button 40px height, right button with icon 41px height).

![Screenshot 2020-06-17 at 10 18 22](https://user-images.githubusercontent.com/3532843/84875221-f7a2c500-b085-11ea-9c56-080f940edfa1.png)

**Comment by pascalwengerter** [comment]
@kulmann tried to replicate this one but wasn't able to, at least in the design guide. Do you happen to remember where you came across this? :)

**Comment by pascalwengerter** [comment]
@kulmann should be fixed with the most recent changes, could you confirm and close this ticket if so?

**Comment by kulmann** [comment]
Apparently buttons with and without have a height of 42px now. So this seems to be solved. Thank you!
