### ISSUE TITLE
Create files list component

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/owncloud-design-system#810]
In ocis-web, we are using a custom files table component. IMHO it would make sense to bring it in here so we can reuse it in some other projects/extensions (e.g. file/location picker).

When bringing it we might also consider using props a bit more to reduce the necessary code where it would be used. This is a nice example of this approach - https://www.vuetable.com/guide/getting-started.html#usage

**Comment by pascalwengerter** [comment]
@kulmann perhaps closed via #1034? 😎

**Comment by kulmann** [comment]
Yes :-)
