### ISSUE TITLE
Notification messages apply wrong variation on icons

### ISSUE THREAD

**Issue by kulmann** [owncloud/owncloud-design-system#843]
The notification message component applies it's `status` property to the `variation` prop of two `oc-icon`s here https://github.com/owncloud/owncloud-design-system/blob/703f71c999607f951ab463ee50a39d814c828ec9/src/elements/OCNotificationMessage.vue#L3 and https://github.com/owncloud/owncloud-design-system/blob/703f71c999607f951ab463ee50a39d814c828ec9/src/elements/OCNotificationMessage.vue#L18

This is a bug, since the prop validation of `status` in `OcNotificationMessage` and `variation` in `OcIcon` don't match. We need to derive icon variation classes from the possible notification message status values.

---
This bug was found because of a well spotted console error from Robert Pocklington:
```
I find calling this code gives a validation error on the params, as if "primary" isn't valid 
this.showMessage({ title: this.$gettext('some message'), status: 'primary' })
, but it's specified here: https://owncloud.design/#/Elements/oc-notification-message
```
![notification-error](https://user-images.githubusercontent.com/3532843/90726660-5b35b280-e2c2-11ea-94cb-f5a31ef8cf34.png)

**Comment by rpocklin** [comment]
Hi @kulmann any chance of an update on this?  Although it works it creates false errors in the console log.

**Comment by kulmann** [comment]
Hey @rpocklin, I made a PR: https://github.com/owncloud/owncloud-design-system/pull/893
We'll release ODS 1.12.1 and update it in phoenix today.
