### ISSUE TITLE
Align styling of oc-switch current style

### ISSUE THREAD

**Issue by kulmann** [owncloud/owncloud-design-system#844]
The styling of the `oc-switch` component is not aligned with the current styling of e.g. oc-button anymore. We need to push it to the next level -> apply our current styling with rounded corners etc.

## current styling of `oc-switch`
<img width="311" alt="Screenshot 2020-08-20 at 14 39 08" src="https://user-images.githubusercontent.com/3532843/90771003-f47cbd00-e2f2-11ea-888b-2dce277c53d8.png">
<img width="233" alt="Screenshot 2020-08-20 at 14 39 13" src="https://user-images.githubusercontent.com/3532843/90771009-f5adea00-e2f2-11ea-9901-83fdbaf67fa7.png">

## current styling of `oc-button`
<img width="949" alt="Screenshot 2020-08-20 at 14 42 00" src="https://user-images.githubusercontent.com/3532843/90771305-5f2df880-e2f3-11ea-9749-80992d9fbcdd.png">

**Comment by pascalwengerter** [comment]
Got fixed in #1421
