### ISSUE TITLE
Small bugs in ODS 1.10.1

### ISSUE THREAD

**Issue by kulmann** [owncloud/owncloud-design-system#877]
ODS 1.10.1 has some visual bugs that need fixing. This is a collection of it, including screenshots.

- [ ] borders around focused ~~raw~~ buttons (borders need to be removed). Actually, all buttons are affected. It's just more obvious on raw buttons. It should be sufficient to have the highlighted color only for `:hover`, not for `:focus`.
<img width="252" alt="Screenshot 2020-09-17 at 17 45 53" src="https://user-images.githubusercontent.com/3532843/93494898-d57f4400-f90d-11ea-91de-30a16686b562.png">

**Comment by kulmann** [comment]
I propose to use `display: inline-flex;` instead of `display: flex;` on oc-buttons. Otherwise we'll have to take care of re-layouting all buttons in any location, since they are handles as block elements and will cause line breaks.

**Comment by LukasHirt** [comment]
The focus is actually on purpose due to accessibility #445

**Comment by kulmann** [comment]
Oh wow... I get the point, but I think that needs to be less obtrusive. Did you also consider some dropshadow, very thin border, etc?

**Comment by LukasHirt** [comment]
Agree that it should be as subtle as possible but on the other hand, we need to consider people with visual impairments though. What we discussed once was the option to visualise the focus only if it was done via the keyboard, not when clicking on elements.

**Comment by kulmann** [comment]
Closing in favor of https://github.com/owncloud/phoenix/issues/3046
