### ISSUE TITLE
component: file action element

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/owncloud-design-system#95]
## screenshots
![Screenshot from 2019-03-25 08-55-10](https://user-images.githubusercontent.com/1005065/54903251-c451a480-4edb-11e9-94a4-ab1fa370ff29.png)

## behavior
- upon clicking a file this action element opens
- a list of actions is displayed
- upon clicking outside of the element it closes
- upon clicking on one of the actions the element closes
- today this is basically a footer bar or something - can change in the future - let's just rebuild what we have

## events
- action click event

## properties
- file name, string
- items, array of objects with icon, name and event callback (??)

**Comment by butonic** [comment]
fixed with https://github.com/owncloud/owncloud-design-system/pull/109 next streps tracked in https://github.com/owncloud/owncloud-design-system/issues/127
