### ISSUE TITLE
component: sidebar

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/owncloud-design-system#96]
## screenshots
![Screenshot from 2019-03-25 09-01-19](https://user-images.githubusercontent.com/1005065/54903594-96209480-4edc-11e9-92d0-7d4b52ac59e1.png)

## behavior
- slides in and out - on mobile we better use a full screen approach - note for later
- has a title and a close button
- within the default slot further inner components can be rendered
- sticks to the app top bar - does not scroll

## events
- close
- open

## properties
- title, string

**Comment by DeepDiver1975** [comment]
in addition to the right sidebar we also need a left side bar

see oc10 webui

![Screenshot from 2019-03-25 11-07-46](https://user-images.githubusercontent.com/1005065/54911223-48148c80-4eee-11e9-8be3-8e75644a39bb.png)

**Comment by tomneedham** [comment]
I presume this will need some higher order thinking on the page layout. Like this:

<img width="677" alt="Screenshot 2019-03-26 at 15 34 53" src="https://user-images.githubusercontent.com/660805/55010782-bafc3100-4fdc-11e9-9214-6dd705e3a66f.png">

And then apps can choose to use those as they need. Files would place the table in the content container, details view in the right sidebar and nav list in the left sidebar

**Comment by tomneedham** [comment]
left and right sidebar, and top nav are anchored, and content container is scrollable

**Comment by DeepDiver1975** [comment]
absolutly - I was missing input for you all which we discussed in scope of phonix some time ago: https://github.com/owncloud/phoenix/issues/433
