### ISSUE TITLE
template: login

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/owncloud-design-system#99]
## screenshot
![Screenshot from 2019-03-25 09-22-09](https://user-images.githubusercontent.com/1005065/54904705-8191cb80-4edf-11e9-93b7-f18b02810d67.png)

## elemets
- footer (own pattern)
- fullscreen base layout
- text elements like h{1-3} and p
- text coloring capabilities - respect contrast color based on background

**Comment by tomneedham** [comment]
Implemented here https://github.com/owncloud/owncloud-design-system/pull/111
